- name: Initialize CodeQL
  uses: github/codeql-action/init@v1
  with:
    languages: 'cpp'
    # If you wish to specify custom queries for CodeQL to execute, you can do so here

# Autobuild step removed because it was failing
# - name: Autobuild
#   uses: github/codeql-action/autobuild@v1

- name: Custom build step
  run: |
    # Replace these lines with the commands to build your project
    gcc Kuznechik_Fast.c -lgmp -fopenmp
    ./a.out

- name: Perform CodeQL Analysis
  uses: github/codeql-action/analyze@v1
